### PR TITLE
Event form submission page cleanup

### LINKED ISSUE #153: Event Submission Form Page
Minor ui polish and cleanup, if there's missing info from the api, disregard until that's complete. If there's missing features, disregard and ticket.

- [ ] Event Submission Form dark mode does not cover entire form
- [ ] Header size for Event Submission Form
- [ ] Organization Details Section missing
- [ ] Event details display layout not in its own display container
- [ ] Event details form layout incorrect, need reordering
- [ ] Need Even Image Upload option display incorrect
- [ ] Add a speaker header/tags not reflecting purple figma design
- [ ] "Other" section not separate
- [ ] Accessibilty Options should be two columns, not three
- [ ] Featured event option needs donation tag box
- [ ] Review button sizing needs correction
- [ ] Form input backgrounds stays white in dark mode
- [ ] No outline for form sections/inputs
- [ ] Text color does not change in dark mode
- [ ] Mobile version not implemented

### PR DESCRIPTION
**Pull request by dashcraft**
## Ticket Description
Fixes #153 

- [x] Event Submission Form dark mode does not cover entire form
- [x] Header size for Event Submission Form
- [x] Organization Details Section missing
- [x] Event details display layout not in its own display container
- [x] Event details form layout incorrect, need reordering
- [x] Need Even Image Upload option display incorrect
- [x] Add a speaker header/tags not reflecting purple figma design
- [x] "Other" section not separate
- [x] Accessibilty Options should be two columns, not three
- [x] Review button sizing needs correction
- [x] Form input backgrounds stays white in dark mode
- [x] No outline for form sections/inputs
- [x] Text color does not change in dark mode
- [x] Mobile version not implemented

## Before and After for UI Updates

Before:
image

image

After:
image
image
image
image

## For PR Reviewer
- [x] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [x] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [x] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [x] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

### CODE REVIEW

**Comment by dashcraft** [comment]
the existing yarn lock is out of date, running locally always nets a new yarn lock meaning at some point we added a package and didn't commit the lockfile

File: src/components/elements/AccessibilityDetailField.jsx [hunk 1]
```diff
@@ -15,13 +15,31 @@ function AccessibilityDetailField({ value, onChange }) {
...
 
   return (
-    <>
-      <label className="block font-bold mb-2">Accessibility Options</label>
-
-      <div className="grid grid-cols-3 bg-white rounded p-6">
-        {ACCESSIBILITY_OPTIONS.map(option => {
+    <div className="grid md:grid-cols-2 bg-white dark:bg-transparent rounded p-6">
+      <section>
+        {ACCESSIBILITY_OPTIONS.slice(0, ACCESSIBILITY_OPTIONS.length/2).map((option) => {
```
Comment (jtorreggiani) [inline src/components/elements/AccessibilityDetailField.jsx:20]: Not blocking, but wondering if it would be more clear if we moved these into variables. 

```JavaScript
const sectionOneOptions = ACCESSIBILITY_OPTIONS.slice(0, ACCESSIBILITY_OPTIONS.length/2);
const sectionTwoOptions = ACCESSIBILITY_OPTIONS.slice((ACCESSIBILITY_OPTIONS.length/2), ACCESSIBILITY_OPTIONS.length);

{sectionOneOptions.map((option) => { ...
{sectionTwoOptions.mpa((option)=> { ..
```

**Comment by jtorreggiani** [comment]
@dashcraft, this is looking much cleaner! I pulled down the branch and played around with this. Looking a lot better! Nothing controversial or worrisome in this PR. I did notice one design issue on mobile for the notes sections. 

I think the probably want to stack these on mobile?
Screen Shot 2022-09-12 at 7 58 47 PM

**Comment by jtorreggiani** [comment]
> the existing yarn lock is out of date, running locally always nets a new yarn lock meaning at some point we added a package and didn't commit the lockfile

@dashcraft, I think the repo is setup to use npm instead of yarn and doesn't have a yarn.lock file on main. If there is a reason to switch to yarn I'm up for it, but we will want to make sure all the build stuff and CI is updated.

**Comment by jtorreggiani** [comment]
One other visual bug with the add social media feature. 

Screen Shot 2022-09-12 at 8 08 24 PM

**Review by jtorreggiani — APPROVED** [review]
@dashcraft, overall this pull request is looking good to me. Added one non-blocking suggestion about the code. I noted a couple visual bugs that we can tackle in this PR or a follow up if we want to keep this PR from growing more. ✅

**Review by Saige243 — DISMISSED** [review]
Looks great! Nice work!

File: src/components/elements/AccessibilityDetailField.jsx (hunk 1 above)
Comment (dashcraft) [reply src/components/elements/AccessibilityDetailField.jsx:20]: fixed
