### PR TITLE
event topics css fix

### LINKED ISSUE #290: Event Topic Field CSS
Options are not visible in dark mode
Screenshot (418)

### PR DESCRIPTION
**Pull request by Rohanfizz**
## Ticket Description
Fixes #290 

## Description of Changes
Fixes CSS of event topics selector

## Before and After for UI Updates

Before:

Screenshot (418)

After:

Screenshot (420)

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

### CODE REVIEW

**Comment by jtorreggiani** [comment]
Thanks @Rohanfizz! This LGTM. Going to merge it in.

**Review by jtorreggiani — APPROVED** [review]

File: src/components/elements/EventTopicField.jsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ function EventTopicField () {
   return (
     <div>
       <label>Topics</label>
-      <Field name="topic" component="select" className={formStyleClasses.select}>
+      <Field name="topic" component="select" className={`${formStyleClasses.select}  dark:bg-[#151A35]`}>
```
Comment (jtorreggiani) [inline src/components/elements/EventTopicField.jsx:10]: @Rohanfizz, I think additional class should be added to the css class object instead of being hardcoded here. Could handle that as a follow up?

**Review by jtorreggiani — APPROVED** [review]

File: src/components/elements/EventTopicField.jsx (hunk 1 above)
Comment (Rohanfizz) [reply src/components/elements/EventTopicField.jsx:10]: Sure, should I do it that way?

Comment (Rohanfizz) [reply src/components/elements/EventTopicField.jsx]: Done✅
